apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis 
  namespace: quay
  labels:
    quay-component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-component: redis
  template:
    metadata:
      labels:
        quay-component: redis
    spec:
      containers:
        - name: redis
          image: altlinux.io/quay/redis
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redisdb
      volumes:
        - name: redisdb
          persistentVolumeClaim:
            claimName: redis-pv-claim
