apiVersion: v1
kind: Service
metadata:
  namespace: quay
  name: quayredis
  labels:
    quay-component: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    quay-component: redis

