apiVersion: v1
kind: Service
metadata:
  name: quay-service
  namespace: quay
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000
  selector:
    quay-component: quay-app
  type: NodePort
