kind: PersistentVolume
apiVersion: v1
metadata:
  name: quay-pv-volume
  labels:
    type: local
    app: quay
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/quaystorage/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker01 
    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: quay-pv-claim
  namespace: quay
  labels:
    quay-component: quay          
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
