version: '3.2'

services:
  quay:
    image: localhost/quay:devel
    #command: config Mypass
    volumes:
      - quay_config:/quay-registry/conf/stack
      - quay_datastorage:/datastorage
      - quay_stack:/conf/stack
    ports:
      - 0.0.0.0:80:8080
      - 0.0.0.0:443:8443

  redis:
    image: redis
    volumes:
      - quay_redis_data:/data


  postgres:
    image: quay/postgres
    volumes:
      - quay_postgres_data:/var/lib/pgsql/data

volumes:
  quay_config:
  quay_datastorage:
  quay_stack:
  quay_redis_data:
  quay_postgres_data:
