version: '3.2'

services:
  quay:
    image: ${regNS}/quay/quay
    #command: config Htubcnhfnjh
    volumes:
      - quay_config:/quay-registry/conf/stack
      - quay_datastorage:/datastorage
      - quay_stack:/conf/stack
    ports:
      - 0.0.0.0:${HTTPPORT}:8080
      - 0.0.0.0:${HTTPSPORT}:8443

  quayredis:
    image: localhost/quay/redis
    volumes:
      - quay_redis_data:/data


  quaydb:
    image: localhost/quay/postgres
    volumes:
      - quay_postgres_data:/var/lib/pgsql/data

volumes:
  quay_config:
  quay_datastorage:
  quay_stack:
  quay_redis_data:
  quay_postgres_data:
