version: '3.2'

services:
  quay:
    image: ${regNS}/quay/quay
    #command: config Htubcnhfnjh
    volumes:
      - quay_config:/quay-registry/conf/stack
      - quay_datastorage:/datastorage
        #- quay_stack:/conf/stack
    ports:
      - ${HTTPPORT}:8080
      - ${HTTPSPORT}:8443
    deploy:
      placement:
        constraints:
        - node.hostname==node3.hub.ics.perm.ru

  quayredis:
    image: ${regNS}/quay/redis
    volumes:
      - quay_redis_data:/data
    deploy:
      placement:
        constraints:
          - node.hostname==node3.hub.ics.perm.ru


  quaydb:
    image: ${regNS}/quay/postgres
    volumes:
      - quay_postgres_data:/var/lib/pgsql/data
    deploy:    
      placement:
        constraints:
          - node.hostname==node3.hub.ics.perm.ru

volumes:
  quay_config:
  quay_datastorage:
  #quay_stack:
  quay_redis_data:
  quay_postgres_data:
